#!/usr/bin/env python3
"""Generate combined security report from Trivy JSON results."""

import json
import os
from datetime import datetime, timezone

def main():
    images = ["agent", "gui", "ollama"]
    report = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "repository": "WhoisMonesh/devops-ai-copilot",
        "commit": os.environ.get("GITHUB_SHA", "unknown"),
        "images": {}
    }

    for img in images:
        json_file = f"trivy-results/trivy-results-{img}.json"
        report["images"][img] = {"vulnerabilities": {}, "config_scan": "available"}

        if os.path.exists(json_file):
            with open(json_file) as f:
                data = json.load(f)
            results = data.get("Results", [])
            summary = {}
            critical_fatal = []

            for r in results:
                vulns = r.get("Vulnerabilities") or []
                for v in vulns:
                    sev = v.get("Severity", "UNKNOWN")
                    summary[sev] = summary.get(sev, 0) + 1
                    if sev == "CRITICAL":
                        critical_fatal.append({
                            "pkg": v.get("PkgName", "unknown"),
                            "installed": v.get("InstalledVersion", "unknown"),
                            "fixed": v.get("FixedVersion", "N/A"),
                            "title": v.get("Title", v.get("Description", "N/A"))[:100]
                        })

            report["images"][img]["vulnerabilities"] = summary
            report["images"][img]["critical_count"] = summary.get("CRITICAL", 0)
            report["images"][img]["high_count"] = summary.get("HIGH", 0)
            report["images"][img]["total_vulns"] = sum(summary.values())
            report["images"][img]["critical_vulns"] = critical_fatal[:10]
        else:
            report["images"][img]["error"] = "Scan results not found"

    # Write JSON report
    with open("security-report.json", "w") as f:
        json.dump(report, f, indent=2)

    # Write Markdown report
    total_critical = sum(img.get("critical_count", 0) for img in report["images"].values())
    total_high = sum(img.get("high_count", 0) for img in report["images"].values())

    with open("security-report.md", "w") as f:
        f.write("# Security Scan Report\n\n")
        f.write(f"**Generated:** {report['generated_at']}  \n")
        f.write(f"**Commit:** `{report['commit']}`  \n")
        f.write(f"**Repository:** {report['repository']}\n\n")
        f.write("---\n\n")

        f.write("## Summary\n\n")
        f.write("| Image | Critical | High | Total |\n")
        f.write("|-------|----------|------|-------|\n")
        for img, data in report["images"].items():
            c = data.get("critical_count", 0)
            h = data.get("high_count", 0)
            t = data.get("total_vulns", 0)
            f.write(f"| {img} | {c} | {h} | {t} |\n")
        f.write("\n")

        for img, data in report["images"].items():
            f.write(f"## {img}\n\n")
            vulns = data.get("vulnerabilities", {})
            if vulns:
                f.write("### Vulnerability Breakdown\n\n")
                for sev in ["CRITICAL", "HIGH", "MEDIUM", "LOW", "UNKNOWN"]:
                    count = vulns.get(sev, 0)
                    if count > 0:
                        f.write(f"- **{sev}:** {count}\n")
                f.write("\n")
            crits = data.get("critical_vulns", [])
            if crits:
                f.write("### Critical Vulnerabilities\n\n")
                for v in crits:
                    f.write(f"- `{v['pkg']}` ({v['installed']})")
                    if v["fixed"] != "N/A":
                        f.write(f" — fixed in `{v['fixed']}`")
                    f.write(f"\n  {v['title']}\n")
            f.write("\n---\n\n")

        f.write("*Report generated by GitHub Actions CI pipeline — Trivy security scanner*\n")

    print(f"Reports generated: security-report.json, security-report.md")
    print(f"Total Critical: {total_critical}, Total High: {total_high}")

if __name__ == "__main__":
    main()
